# Generated by Django 3.0.7 on 2020-07-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Nas',
        ),
        migrations.DeleteModel(
            name='Radacct',
        ),
        migrations.DeleteModel(
            name='Radcheck',
        ),
        migrations.DeleteModel(
            name='Radgroupcheck',
        ),
        migrations.DeleteModel(
            name='Radgroupreply',
        ),
        migrations.DeleteModel(
            name='Radpostauth',
        ),
        migrations.DeleteModel(
            name='Radreply',
        ),
        migrations.DeleteModel(
            name='Radusergroup',
        ),
    ]
