# Generated by Django 3.0.7 on 2020-07-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_auto_20200723_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseraccessSelectedpackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.CharField(max_length=10)),
                ('speed', models.CharField(max_length=10)),
                ('expiry', models.CharField(db_column='Expiry', max_length=50)),
                ('balance', models.CharField(max_length=100)),
                ('access_period', models.CharField(max_length=10)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'useraccess_selectedpackages',
                'managed': False,
            },
        ),
    ]
