# Generated by Django 3.0.7 on 2020-06-16 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phonenumber', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.CharField(max_length=20)),
                ('bundle_price', models.IntegerField()),
                ('bundle_length', models.CharField(max_length=10)),
                ('bundle_speed', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('bundle', models.CharField(max_length=10)),
                ('speed', models.CharField(max_length=10)),
                ('Expiry', models.CharField(max_length=50)),
                ('balance', models.CharField(max_length=100)),
                ('access_period', models.CharField(max_length=10)),
            ],
        ),
    ]
